exports.module = { resource: '/challenge',
    path: '/challenge',
    httpMethod: 'POST',
    queryStringParameters: null,
    multiValueQueryStringParameters: null,
    pathParameters: null,
    stageVariables: null,
    requestContext: 
    { resourceId: 'jp299q',
    resourcePath: '/challenge',
    httpMethod: 'POST',
    requestTime: '29/Mar/2019:00:10:43 +0000',
    path: '/nonprod/challenge',
    protocol: 'HTTP/1.1',
    stage: 'nonprod',
    identity: 
    { cognitoIdentityPoolId: null,
    accountId: null,
    cognitoIdentityId: null,
    caller: null,
    accessKey: null,
    cognitoAuthenticationType: null,
    cognitoAuthenticationProvider: null,
    userArn: null,
    userAgent: 'Slackbot 1.0 (+https://api.slack.com/robots)',
    user: null }},
    body: 'token=jJeiz0IEatqzDoktydPGxKOA&channel_name=directmessage&user_name=trevor.creed&command=%2Fchallenge&text=&response_url=https%3A%2F%2Fhooks.slack.com%2Fcommands%2FT4TE8RPPY%2F589975528432%2FKWuPrEiap3DgCn3E1niITKw8&trigger_id=593465948791.163484873814.46d9ecc68a4e7260675804787a4b62c4',
    isBase64Encoded: false }